### ISSUE TITLE
Teleport Delay not functional

### ISSUE THREAD

**Issue by Swaiguy** [saefulbarkah/fun-games#2]
This problem only started today. The countdown popup shows up in game but it doesn't have any effect and is ignored.

Otherwise, An Absolutely Fantastic and Kind mod! THANKYOU!!

Been using it to speedrun my content since I previously played wuwa on my main!
Also noticed some options are missing from yesterday. Options that didnt work albeit so its interesting this mod auto-updates itself?

Have a great day mate~~

**Comment by saefulbarkah** [comment]
> This problem only started today. The countdown popup shows up in game but it doesn't have any effect and is ignored.
> 
> Otherwise, An Absolutely Fantastic and Kind mod! THANKYOU!!
> 
> Been using it to speedrun my content since I previously played wuwa on my main! Also noticed some options are missing from yesterday. Options that didnt work albeit so its interesting this mod auto-updates itself?
> 
> Have a great day mate~~

Delay issue already fix. yes this mod auto update because im lazy to upload and write every changes.
